django/0831/pjt1/articles/urls.py
from django.urls import path
from . import views

# app_name = 'articles'
urlpatterns = [
    path('catch/', views.catch, name='catch'),
    path('index/', views.index, name='index'),
]

django/0831/pjt1/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('index/', views.index, name='index'),
]

django/0831/pjt1/pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('pages/', include('pages.urls')),
]

django/0831/pjt1/articles/models.py
from django.db import models

# Create your models here.

django/0831/pjt1/pages/models.py
from django.db import models

# Create your models here.

django/0831/pjt1/articles/views.py
from django.shortcuts import render

# Create your views here.
def catch(request):
    return render(request, 'articles/catch.html')

def index(request):
    return render(request, 'articles/index.html')

django/0831/pjt1/pages/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

django/0831/pjt1/articles/templates/articles/catch.html
{% extends 'base.html' %}

{% block content %}
  <h1>catch</h1>
  <a href="{% url 'articles:index' %}">articles의 index로</a>
  <a href="{% url 'pages:index' %}">pages의 index로</a>
{% endblock content %}

django/0831/pjt1/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>articles의 index</h1>
  <a href="{% url 'articles:catch' %}">catch로</a>
{% endblock content %}

django/0831/pjt1/pages/templates/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>pages의 index</h1>
  <a href="{% url 'articles:catch' %}">catch로</a>
{% endblock content %}

django/0831/pjt1/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {% block content %}{% endblock content %}
</body>
</html>